# Generated by Django 4.1.7 on 2023-03-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soundclip',
            name='location',
        ),
        migrations.AlterField(
            model_name='soundclip',
            name='file',
            field=models.FileField(upload_to='sound/None/'),
        ),
    ]
