# Generated by Django 4.1.7 on 2023-02-28 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_message_options_soundclip_commenters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundclip',
            name='commenters',
            field=models.ManyToManyField(blank=True, related_name='commenters', to=settings.AUTH_USER_MODEL),
        ),
    ]
