# Generated by Django 4.1.7 on 2023-02-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_soundclip_commenters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundclip',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
